### ISSUE TITLE
[BUG] React Query 통신 무한 요청 문제

### ISSUE THREAD

**Issue by Mark1237200** [codestates-seb/seb39_main_038#170]
# 증상

내용: GET 통신을 시도 할때마다 성공 유무 상관없이 무한적으로 이루어 집니다.

수정할 내용: 최초 통신을 시도하고, 통신이 멈추거나 실패시 한번더 재요청하고 멈춰야 합니다.

날짜: 2022-10-03

# 참고 링크 & 스크린샷

![문제점4](https://user-images.githubusercontent.com/99641988/193570708-f1a64a81-06ef-4aa3-b3ff-bae67e15cabd.png)

Link: https://velog.io/@bak_chun8/React-Query-%EC%82%AC%EC%9A%A9%EA%B8%B0

**Comment by YHJ96** [comment]
확인했습니다!! 재원님이 알려준 옵션으로 defaultOptions 옵션 설정하겠습니다
