### ISSUE TITLE
[BUG] onClick 로 만든 함수를 두번 클릭해야 작동합니다

### ISSUE THREAD

**Issue by Mark1237200** [codestates-seb/seb39_main_038#173]
# 증상

내용: onClick 함수에 메뉴를 클릭시 setRecoilState에 담기도록 state(메뉴)로 짜 두었습니다. 잘 작동되지만
         메뉴를 2번 눌러야 합니다. 첫번째 눌렀을때는 무반응, 두번째 누르면 첫번째 눌렀던 정보가 출력이
         됩니다! onclick 함수 밖에 state를 둘 경우 무한루프로 빠져 페이지가 고장납니다.

```javascript
// 리코일 상태관리
const [receipt, setReceipt] = useRecoilState(atoms.menuOrder);
const [orderList, setOrderList] = useRecoilState(atoms.orderList);

// 메뉴 data를 넘기는 과정
const [defaultObj, ...rest] = receipt;
<Menu
      key={menu.id}
      onClick={() => {
        setOrderList(rest);

        return setReceipt([
          ...receipt,
          {
            count: 1,
            id: menu.id,
            name: menu.name,
            price: menu.price,
          },
        ]);
      }}
    >

// atoms 
  menuOrder: atom({
    key: 'menuOrder',
    default: [{ name: '', price: null, id: null, count: null }],
  }),

  orderList: atom({
    key: 'orderList',
    default: [],
    effects: [sessionStorageEffect('orderList')],
  }),

// sessionStorageEffect
isLogin: atom({
    key: 'isLogin',
    default: { state: false, type: null },
    effects: [sessionStorageEffect('isLogin')],
  }),
```

수정할 내용: 
날짜: 2022-10-03

# 참고 링크 & 스크린샷

**리코일State를 전역에 둘경우**
![문제점6](https://user-images.githubusercontent.com/99641988/193586193-bb7742ae-5b50-4996-977b-f7244e8a394f.png)

**3번 치킨 햄버거 피자를 누른경우**
![image](https://user-images.githubusercontent.com/99641988/193586673-42b39fcc-fd66-4d8e-8239-4caf440f80f6.png)

Link: https://higher77.tistory.com/72

**Comment by YHJ96** [comment]
[PR] 장바구니 기능 구현 완료 #181
버그 수정 완료했습니다.
