### ISSUE TITLE
[BUG] register 부분 Input 태그들이 네비게이션바를 침범합니다

### ISSUE THREAD

**Issue by Mark1237200** [codestates-seb/seb39_main_038#200]
# 증상

내용: input 창들이 네비게이션바를 침범해 겹치게 보입니다 ( 윈도우창 높이를 줄일시 )
수정할 내용: 네비게이션바와 겹치지 않아야 합니다
날짜:  2022-10-05

# 참고 링크 & 스크린샷

![image](https://user-images.githubusercontent.com/99641988/193974130-489498c1-8cf5-4c2a-ab29-422f6035152f.png)

**Comment by YHJ96** [comment]
[PR] 중첩 화면 UI 수정 완료 #206 
버그 수정 완료했습니다.
